name:                filesort
version:             0.1.0.0
github:              "naushadh/filesort"
license:             BSD3
author:              "Naushadh"
maintainer:          "naushadh@protonmail.com"
copyright:           "2018 Naushadh"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/naushadh/filesort#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- streamly
- cassava
- vector
- vector-algorithms
- temporary
- directory

library:
  source-dirs: src

executables:
  filesort:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - filesort
    - optparse-applicative

  filesort-gen:
    main:                Main.hs
    source-dirs:         gen
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - filesort
    - optparse-applicative

tests:
  filesort-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - filesort
